### ISSUE TITLE
BUG + Solution: Typechecker crash

### ISSUE THREAD

**Issue by RomanCastellarin** [compiladores-lcc/compiladores#1]
**bug:** TypeChecker crashes (ungracefully) on certain ill-typed terms

**how to reproduce:** In interactive mode, enter: `fix (f: Nat -> Nat) (x: Nat) -> fun (y: Nat) -> x`
which halts execution and prompts the message: `INTERNAL ERROR: openN: M is not LC`
Similarly, entering `fix (f: Nat -> Nat -> Nat) (x: Nat) -> x`
yields `Error de tipo en (Bound 0)`

**solution**
In function `tc` from module `TypeChecker` (case definition for `Fix`)
change the following lines (56 and 57) from this:
```
         ty' <- tc (openN [f, x] t) ((x,xty):(f,fty):bs)
         expect cod ty' t
```
to this:
```
         let t' = openN [f, x] t
         ty' <- tc t' ((x,xty):(f,fty):bs)
         expect cod ty' t'
```
_explanation_: if `cod` and `ty'` mismatch, expect tries to pretty-print term `t`, which should have been previously opened.

**Comment by mjaskelioff** [comment]
Gracias Román!
